### PR TITLE
[Tournament] Fix #32 Team password hashing

### LINKED ISSUE #32: Team password hashing
As the team name is used in the password hashing as follows :
 ```PHP
$container = $this->getConfigurationPool()->getContainer();
$factory = $container->get('security.encoder_factory');
$encoder = $factory->getEncoder(new User());
$e->setPassword($encoder->encodePassword($e->getPlainPassword(), sha1('pleaseHashPasswords'.$e->getName())));
```
it is currently impossible to change the team name without changing the associated password !

### PR DESCRIPTION
**Pull request by Teanan**
Team passwords hashs no longer tied to team name

### CODE REVIEW

**Comment by Lesterpig** [comment]
Thanks! Pretty sure @halfa would be the best for this review ;)

**Comment by halfa** [comment]
Just flew over the code, seems OK to me 👍
I'll do a dry migration on prod-like data tomorrow just in case,  holding the merge until then.

**Comment by nhurman** [comment]
So British!

**Comment by halfa** [comment]
My `master` was off (938352c missing) so the historic is a bit weird but whatever.
LGTM, ready for prod!

**Pull request merged**
