### PR TITLE
Navbar update

### PR DESCRIPTION
**Pull request by FoxyHawk**
Smaller navbar with sticky behavior.
More modern css and better consistency overall.
New logo updated.

### CODE REVIEW

**Comment by AntoineBvn** [comment]
The navbar of admin interface is broken. Can you fix it ?

**Comment by FoxyHawk** [comment]
I did not expect to find a copy of the layout in the admin bundle...
1-2h before fix

**Comment by FoxyHawk** [comment]
The logo for admin is a placeholder. I am waiting on the art team to get the definitive one.

**Comment by AntoineBvn** [comment]
It's fine for me. Thanks

**Pull request merged**
